---
# AutoClearLagg (ACL) Config

# Seconds between each clear lagg
seconds: 300

# Entities to clear
clear:
  items: true
  mobs: true
  xp-orbs: true
  exempt: # Array of entities not to clear
    - Zombie
    - Pig

messages:
  time-left: "§cลบขยะในอีก {SECONDS} วินาที"
  entities-cleared: "§cขยะถูกลบ {COUNT} ชิ้น"

# Countdown times
times: [60, 30, 15, 10, 5, 4, 3, 2, 1]
...
