---
# AutoClearLagg (ACL) Config

# Seconds between each clear lagg
seconds: 500

# Entities to clear
clear:
  items: true
  mobs: false
  xp-orbs: true
  exempt: # Array of entities not to clear
    - Zombie
    - Pig

messages:
  time-left: "§cลบขยะตามพื้นในอีก {SECONDS} วินาที"
  entities-cleared: "§cขยะตามพื้นถูกลบ {COUNT} ชิ้น"

# Countdown times
times: [10, 5, 4, 3, 2, 1]
...
